# Site settings
title: Tyler Voss
description: A blog about lorem ipsum dolor sit amet
# baseurl: 
# url: 

# User settings
username: Tyler Voss
user_description: Computer Engineering with a Business Minor finishing up my Senior year at the Univeristy of Illinois at Urbana Champaign. Lead software development intern for U of I Sports Technology, freelance mobile application developer, and former Fraternity President.
user_title: Computer Engineer
email: tVoss42@gmail.com
twitter_username:
github_username:  tVoss
gplus_username:

# Google-analytics
google-analytics:
  id: "UA-98604018-1"

exclude: ['package.json', 'src' , 'node_modules']
