# Site settings
title: Tyler Voss
description: A blog about lorem ipsum dolor sit amet
# baseurl: 
# url: 

# User settings
username: Tyler Voss
user_description: Computer Engineering Junior at Univeristy of Illinois at Urbana Champaign. Lead software development intern for the Division of Intercollegate Athletics and former Fraternity President.
user_title: Computer Engineer
email: tVoss42@gmail.com
twitter_username:
github_username:  tVoss
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
